version: '3.9'
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - backend
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://backend:4000
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '4000:4000'
    depends_on:
      - mongo
    environment:
      - NODE_ENV=production
      - PORT=4000
      - MONGO_URI=mongodb://mongo:27017/student-risk-system
      - FRONTEND_URL=http://localhost:3000
  ml:
    image: tiangolo/uvicorn-gunicorn-fastapi:python3.11
    volumes:
      - ./backend/src/ml:/app
    ports:
      - '8001:8001'
    command: uvicorn main:app --host 0.0.0.0 --port 8001 --reload
  mongo:
    image: mongo:7.0
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
volumes:
  mongo-data:
    name: student-risk-system-mongo
